version: "3.6"

services:
  wifi-manager:
    #build: ./wifi-connect # Doesn't work with podman yet
    image: docker.io/mgoltzsche/wifi-manager:dev
    cap_add:
    - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    network_mode: host
    restart: unless-stopped
    volumes:
    - "/:/host"
